namespace vkinegrab.Services;

internal static class CountryCodeMapper
{
    private static readonly Dictionary<string, string> CsfdCzechNameToIsoAlpha2 = new(StringComparer.Ordinal)
    {
        ["afghánistán"] = "AF",
        ["albánie"] = "AL",
        ["alžírsko"] = "DZ",
        ["andorra"] = "AD",
        ["anglie"] = "GB",
        ["angola"] = "AO",
        ["antigua a barbuda"] = "AG",
        ["argentina"] = "AR",
        ["arménie"] = "AM",
        ["aruba"] = "AW",
        ["austria hungary"] = "AH",
        ["austro hungarian empire"] = "AH",
        ["austrálie"] = "AU",
        ["bahamy"] = "BS",
        ["bahrajn"] = "BH",
        ["bangladéš"] = "BD",
        ["barbados"] = "BB",
        ["barma"] = "BU",
        ["belgian congo"] = "CD",
        ["belgické kongo"] = "CD",
        ["belgie"] = "BE",
        ["belize"] = "BZ",
        ["benin"] = "BJ",
        ["bhútán"] = "BT",
        ["bolívie"] = "BO",
        ["bosna a hercegovina"] = "BA",
        ["botswana"] = "BW",
        ["brazílie"] = "BR",
        ["brunej"] = "BN",
        ["bulharsko"] = "BG",
        ["burkina faso"] = "BF",
        ["burma"] = "BU",
        ["burundi"] = "BI",
        ["byelorussian ssr"] = "BY",
        ["bělorusko"] = "BY",
        ["ceylon"] = "LK",
        ["chile"] = "CL",
        ["chorvatsko"] = "HR",
        ["curacao"] = "CW",
        ["czechoslovakia"] = "CS",
        ["dahome"] = "BJ",
        ["dahomey"] = "BJ",
        ["demokratická republika kongo"] = "CD",
        ["dominika"] = "DM",
        ["dominikánská republika"] = "DO",
        ["dánsko"] = "DK",
        ["dánsko norské království"] = "DK",
        ["džibutsko"] = "DJ",
        ["east germany"] = "DD",
        ["east timor"] = "TP",
        ["egypt"] = "EG",
        ["ekvádor"] = "EC",
        ["eritrea"] = "ER",
        ["estonsko"] = "EE",
        ["etiopie"] = "ET",
        ["faerské ostrovy"] = "FO",
        ["fed rep jugoslávie"] = "YU",
        ["federal republic of yugoslavia"] = "YU",
        ["federativní státy mikronésie"] = "FM",
        ["fidži"] = "FJ",
        ["filipíny"] = "PH",
        ["finsko"] = "FI",
        ["francie"] = "FR",
        ["francouzská polynésie"] = "PF",
        ["gabon"] = "GA",
        ["gambie"] = "GM",
        ["german democratic republic"] = "DD",
        ["german empire"] = "DE",
        ["germany"] = "DE",
        ["ghana"] = "GH",
        ["grenada"] = "GD",
        ["gruzie"] = "GE",
        ["grónsko"] = "GL",
        ["guadeloupe"] = "GP",
        ["guatemala"] = "GT",
        ["guinea"] = "GN",
        ["guinea bissau"] = "GW",
        ["guyana"] = "GY",
        ["haiti"] = "HT",
        ["honduras"] = "HN",
        ["hongkong"] = "HK",
        ["horní volta"] = "HV",
        ["indie"] = "IN",
        ["indonésie"] = "ID",
        ["irsko"] = "IE",
        ["irák"] = "IQ",
        ["island"] = "IS",
        ["itálie"] = "IT",
        ["izrael"] = "IL",
        ["jamajka"] = "JM",
        ["japonsko"] = "JP",
        ["jemen"] = "YE",
        ["jihoafrická republika"] = "ZA",
        ["jihozápadní afrika"] = "NA",
        ["jižní jemen"] = "YD",
        ["jižní korea"] = "KR",
        ["jižní rhodesie"] = "ZW",
        ["jižní vietnam"] = "VN",
        ["jordánsko"] = "JO",
        ["jugoslávie"] = "YU",
        ["kambodža"] = "KH",
        ["kamerun"] = "CM",
        ["kanada"] = "CA",
        ["kapverdy"] = "CV",
        ["katar"] = "QA",
        ["kazachstán"] = "KZ",
        ["keňa"] = "KE",
        ["kiribati"] = "KI",
        ["kldr"] = "KP",
        ["kolumbie"] = "CO",
        ["komory"] = "KM",
        ["kongo"] = "CG",
        ["kongská demokratická republika"] = "CD",
        ["konžská demokratická republika"] = "CD",
        ["korea"] = "KR",
        ["korejská republika"] = "KR",
        ["kosovo"] = "XK",
        ["kostarika"] = "CR",
        ["království srbů chorvatů a slovinců"] = "YU",
        ["kréta"] = "GR",
        ["kuba"] = "CU",
        ["kuvajt"] = "KW",
        ["kypr"] = "CY",
        ["kyrgyzstán"] = "KG",
        ["laos"] = "LA",
        ["lesotho"] = "LS",
        ["libanon"] = "LB",
        ["libye"] = "LY",
        ["libérie"] = "LR",
        ["lichtenštejnsko"] = "LI",
        ["litva"] = "LT",
        ["lotyšsko"] = "LV",
        ["lucembursko"] = "LU",
        ["macao"] = "MO",
        ["madagaskar"] = "MG",
        ["makedonie"] = "MK",
        ["malajsie"] = "MY",
        ["malawi"] = "MW",
        ["maledivy"] = "MV",
        ["mali"] = "ML",
        ["malta"] = "MT",
        ["maroko"] = "MA",
        ["marshallovy ostrovy"] = "MH",
        ["martinik"] = "MQ",
        ["mauricius"] = "MU",
        ["mauritánie"] = "MR",
        ["mayotte"] = "YT",
        ["maďarsko"] = "HU",
        ["maďarské království"] = "HU",
        ["mexiko"] = "MX",
        ["moldavsko"] = "MD",
        ["moldavská sovětská socialistická republika"] = "MD",
        ["monako"] = "MC",
        ["mongolsko"] = "MN",
        ["mosambik"] = "MZ",
        ["myanmar"] = "MM",
        ["namibie"] = "NA",
        ["nauru"] = "NR",
        ["ndr"] = "DD",
        ["nepál"] = "NP",
        ["netherlands antilles"] = "AN",
        ["nezávislý stát chorvatsko"] = "HR",
        ["niger"] = "NE",
        ["nigérie"] = "NG",
        ["nikaragua"] = "NI",
        ["nizozemsko"] = "NL",
        ["nizozemské antily"] = "AN",
        ["norsko"] = "NO",
        ["north vietnam"] = "VN",
        ["north yemen"] = "YE",
        ["northern rhodesia"] = "ZM",
        ["nová kaledonie"] = "NC",
        ["nový zéland"] = "NZ",
        ["nsr"] = "DE",
        ["německo"] = "DE",
        ["německá demokratická republika"] = "DD",
        ["německá říše"] = "DE",
        ["německé císařství"] = "DE",
        ["německý spolek"] = "DE",
        ["omán"] = "OM",
        ["osmanská říše"] = "OT",
        ["ottoman empire"] = "OT",
        ["pakistán"] = "PK",
        ["palau"] = "PW",
        ["palestina"] = "PS",
        ["panama"] = "PA",
        ["papua nová guinea"] = "PG",
        ["paraguay"] = "PY",
        ["persia"] = "IR",
        ["persie"] = "IR",
        ["peru"] = "PE",
        ["pobřeží slonoviny"] = "CI",
        ["polsko"] = "PL",
        ["portoriko"] = "PR",
        ["portugalsko"] = "PT",
        ["protektorát čechy a morava"] = "CZ",
        ["prusko"] = "DE",
        ["pákistán"] = "PK",
        ["rakousko"] = "AT",
        ["rakousko uhersko"] = "AH",
        ["rakouské císařství"] = "AT",
        ["rhodesia"] = "RH",
        ["rhodesie"] = "RH",
        ["rovníková guinea"] = "GQ",
        ["rumunsko"] = "RO",
        ["rusko"] = "RU",
        ["ruská federace"] = "RU",
        ["ruské impérium"] = "RU",
        ["rwanda"] = "RW",
        ["saint pierre a miquelon"] = "PM",
        ["salvador"] = "SV",
        ["samoa"] = "WS",
        ["san marino"] = "SM",
        ["saúdská arábie"] = "SA",
        ["senegal"] = "SN",
        ["serbia and montenegro"] = "CS",
        ["severní jemen"] = "YE",
        ["severní korea"] = "KP",
        ["severní makedonie"] = "MK",
        ["severní rhodesie"] = "ZM",
        ["severní vietnam"] = "VN",
        ["seychely"] = "SC",
        ["siam"] = "TH",
        ["sierra leone"] = "SL",
        ["singapur"] = "SG",
        ["sjednocená arabská republika"] = "UAR",
        ["slovensko"] = "SK",
        ["slovenská republika"] = "SK",
        ["slovenský stát"] = "SK",
        ["slovinsko"] = "SI",
        ["socialist federal republic of yugoslavia"] = "YU",
        ["somálsko"] = "SO",
        ["south vietnam"] = "VN",
        ["south west africa"] = "NA",
        ["south yemen"] = "YD",
        ["southern rhodesia"] = "ZW",
        ["soviet union"] = "SU",
        ["sovětský svaz"] = "SU",
        ["sovětský svaz republik"] = "SU",
        ["spojená arabská republika"] = "UAR",
        ["spojené arabské emiráty"] = "AE",
        ["spojené království"] = "GB",
        ["spojené státy"] = "US",
        ["spojené státy americké"] = "US",
        ["spolková republika německo"] = "DE",
        ["srbsko"] = "RS",
        ["srbsko a černá hora"] = "CS",
        ["srí lanka"] = "LK",
        ["sssr"] = "SU",
        ["středoafrická republika"] = "CF",
        ["surinam"] = "SR",
        ["svatá lucie"] = "LC",
        ["svatá říše římská"] = "DE",
        ["svatý kryštof a nevis"] = "KN",
        ["svatý tomáš a princův ostrov"] = "ST",
        ["svatý vincenc a grenadiny"] = "VC",
        ["svazijsko"] = "SZ",
        ["swaziland"] = "SZ",
        ["súdán"] = "SD",
        ["sýrie"] = "SY",
        ["tanzanie"] = "TZ",
        ["tchaj wan"] = "TW",
        ["thajsko"] = "TH",
        ["tibet"] = "CN",
        ["togo"] = "TG",
        ["tonga"] = "TO",
        ["trinidad a tobago"] = "TT",
        ["tunisko"] = "TN",
        ["turecko"] = "TR",
        ["turkmenistán"] = "TM",
        ["tuvalu"] = "TV",
        ["tádžikistán"] = "TJ",
        ["uganda"] = "UG",
        ["uhersko"] = "HU",
        ["uherské království"] = "HU",
        ["ukrainian ssr"] = "UA",
        ["ukrajina"] = "UA",
        ["union of soviet socialist republics"] = "SU",
        ["united arab republic"] = "UAR",
        ["upper volta"] = "HV",
        ["uruguay"] = "UY",
        ["usa"] = "US",
        ["ussr"] = "SU",
        ["uzbekistán"] = "UZ",
        ["vanuatu"] = "VU",
        ["vatikán"] = "VA",
        ["vatikánský městský stát"] = "VA",
        ["velká británie"] = "GB",
        ["venezuela"] = "VE",
        ["vietnam"] = "VN",
        ["východní německo"] = "DD",
        ["východní timor"] = "TP",
        ["wallis a futuna"] = "WF",
        ["weimar republic"] = "DE",
        ["weimarská republika"] = "DE",
        ["west germany"] = "DE",
        ["yugoslavia"] = "YU",
        ["zair"] = "ZR",
        ["zaire"] = "ZR",
        ["zambie"] = "ZM",
        ["zimbabwe"] = "ZW",
        ["západní německo"] = "DE",
        ["ázerbájdžán"] = "AZ",
        ["írán"] = "IR",
        ["čad"] = "TD",
        ["černá hora"] = "ME",
        ["česko"] = "CZ",
        ["československo"] = "CS",
        ["česká a slovenská federativní republika"] = "CS",
        ["česká republika"] = "CZ",
        ["čína"] = "CN",
        ["řecko"] = "GR",
        ["šalamounovy ostrovy"] = "SB",
        ["španělsko"] = "ES",
        ["švazijsko"] = "SZ",
        ["švédsko"] = "SE",
        ["švédsko norská unie"] = "SE",
        ["švýcarsko"] = "CH"
    };

    public static List<string> MapToIsoAlpha2(IEnumerable<string>? originCountries)
    {
        if (originCountries == null)
        {
            return new List<string>();
        }

        var mapped = new List<string>();

        foreach (var item in originCountries)
        {
            if (string.IsNullOrWhiteSpace(item))
            {
                continue;
            }

            var normalized = Normalize(item);
            if (CsfdCzechNameToIsoAlpha2.TryGetValue(normalized, out var iso))
            {
                if (!mapped.Contains(iso, StringComparer.OrdinalIgnoreCase))
                {
                    mapped.Add(iso);
                }

                continue;
            }

            var upper = item.Trim().ToUpperInvariant();
            if ((upper.Length == 2 || upper.Length == 3) && upper.All(char.IsLetter))
            {
                if (!mapped.Contains(upper, StringComparer.OrdinalIgnoreCase))
                {
                    mapped.Add(upper);
                }
            }
        }

        return mapped;
    }

    private static string Normalize(string value)
    {
        var lower = value.Trim().ToLowerInvariant();
        var cleaned = lower
            .Replace('-', ' ')
            .Replace('/', ' ')
            .Replace('.', ' ')
            .Replace(',', ' ')
            .Replace('(', ' ')
            .Replace(')', ' ');

        return string.Join(' ', cleaned.Split(' ', StringSplitOptions.RemoveEmptyEntries));
    }
}
